import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles(() => ({
  rightOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    textAlign: "center",
    color: "white",
    zIndex: 1,
  },
  leftOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    textAlign: "center",
    color: "white",
    zIndex: 1,
  },
  imageContainer: {
    position: "relative",
    zIndex: 0,
    height: "100%",
  },
  rightImage: {
    backgroundImage: `url("https://as2.ftcdn.net/v2/jpg/05/33/82/33/1000_F_533823359_Fkt7O0BapHm4ykF7t6hb6Rl6bCtUhd46.jpg")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    position: "relative",
    height: "93.5%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
  },
}));
